language: c
sudo: required
dist: trusty

services:
  - docker

before_script:
  - docker build -t dell-recovery-ubuntu -f docker/Dockerfile-ubuntu .

script:
  - docker run -t -v `pwd`:/build/dell-recovery -v `pwd`/dist:/build dell-recovery-ubuntu

deploy:
  provider: releases
  api_key: 
    secure: "PRxoEogzz5GAdBQqmNZ6+Vng21wsNn306oaYt39m6ihVBjxdnueH7KJGKXbL6V5PkDCibrtFc0NVVHto2xhVt8KHgVdjjRX8ph5rhGzg0ciRh+Z5TtIRZNjWD1ssmybvFaJE3qyVZWgR2qBqNTzFTwh6IMfM8tKSbaSL56fIFvaPjpc0GvRODCZFzmMRQMUDVfoEQPN+ypDh/xgHu80NqcfMJGtCIQtTLDVSVdK40enWml317T9T51Y8hX3F7LcV/3HiMZItqne9iepXjooQ3q69Jc29O+Z8+7LTVRbPU0lW1LmiCTF2ZKMnb/+mkujnMcVBq8cLc1sMo2u8QdPReq9w72CQEusSdrz6mHXAbzfuWiArHTTIwAFbsPcxPqaAdSBnC4nsAKSIw3GrLZC6e+cr1Qs89LC2zKE694+R8g93XWIouQ5l5GD02cqY1D0t7QxA+eJ8gJRudPuWAWJaFFG71nFggYvRk/mS1ID9bFTmLaDMqb1afgqmMD3hO7A9F8bp0mlr6wIS2CX47Ndu9alYLPylZBnrRC7AFsTJswXFRT/ewqxSzyy8EBh8VyLuu7t3YnbbHWOfdRdqDoVpn4nhZ22ypMwgpPjVu9xoAxpIscWS2iyok1BnHqno9IrXygBVz8uSrEAsme06ZTUm/uGecX69tweCAw0z4U1iUGY="
  file_glob: true
  file: dist/*.deb
  skip_cleanup: true
  on:
    tags: true
    branch: master
